import type { EstudoState } from "./types";

let counter = 0;
const id = (prefix: string) => `${prefix}-${++counter}-${Date.now().toString(36)}`;

export function criarEstudoExemplo(): EstudoState {
  return {
    nomeProjeto: "Santo Antônio Studios",
    terreno: {
      areaTerreno: 598,
      valorTerrenoTotal: 1500000,
      areaTotalConstruida: 0,
    },
    parametros: {
      tributacaoPct: 0.04,
      corretagemUnidadePct: 0.05,
      corretagemTerrenoPct: 0,
      vmvPct: 0.014,
      metaIncorporadorPct: 0.15,
      metaConstrutorPct: 0.1,
    },
    unidades: [
      {
        id: id("un"),
        nome: "Loja frontal",
        qtd: 1,
        areaPrivativaCoberta: 0,
        areaPrivativaDiferente: 40.39,
        areaVagaGaragem: 0,
        areaEquivalenteTotal: 24.234,
        precoVendaUnitM2: 6000,
        deflatorAreaDescoberta: 0,
        cucM2: 2504.8,
        qtdSubRogada: 0,
      },
      {
        id: id("un"),
        nome: "Apt 01 - área privativa com vaga de garagem",
        qtd: 1,
        areaPrivativaCoberta: 35.49,
        areaPrivativaDiferente: 27.74,
        areaVagaGaragem: 12.5,
        areaEquivalenteTotal: 62.6796,
        precoVendaUnitM2: 10000,
        deflatorAreaDescoberta: 0,
        cucM2: 2504.8,
        qtdSubRogada: 0,
      },
      {
        id: id("un"),
        nome: "Apt 02 - área privativa com vaga de garagem",
        qtd: 1,
        areaPrivativaCoberta: 34.04,
        areaPrivativaDiferente: 22.1,
        areaVagaGaragem: 12.5,
        areaEquivalenteTotal: 58.0496,
        precoVendaUnitM2: 10000,
        deflatorAreaDescoberta: 0,
        cucM2: 2504.8,
        qtdSubRogada: 0,
      },
      {
        id: id("un"),
        nome: "Apt 03 - área privativa com vaga de garagem",
        qtd: 1,
        areaPrivativaCoberta: 34.09,
        areaPrivativaDiferente: 22.27,
        areaVagaGaragem: 12.5,
        areaEquivalenteTotal: 58.5446,
        precoVendaUnitM2: 10000,
        deflatorAreaDescoberta: 0,
        cucM2: 2504.8,
        qtdSubRogada: 0,
      },
      {
        id: id("un"),
        nome: "Apt 04 - área privativa com vaga de garagem",
        qtd: 1,
        areaPrivativaCoberta: 33.56,
        areaPrivativaDiferente: 20.23,
        areaVagaGaragem: 12.5,
        areaEquivalenteTotal: 56.9946,
        precoVendaUnitM2: 10000,
        deflatorAreaDescoberta: 0,
        cucM2: 2504.8,
        qtdSubRogada: 0,
      },
      {
        id: id("un"),
        nome: "Apt 05, 10, 11, 16, 17, 22 - sem vaga de garagem",
        qtd: 6,
        areaPrivativaCoberta: 35.49,
        areaPrivativaDiferente: 0,
        areaVagaGaragem: 0,
        areaEquivalenteTotal: 55.0596,
        precoVendaUnitM2: 8500,
        deflatorAreaDescoberta: 0,
        cucM2: 2504.8,
        qtdSubRogada: 0,
      },
      {
        id: id("un"),
        nome: "Apt 06, 09, 12, 15, 18, 21 - sem vaga de garagem",
        qtd: 6,
        areaPrivativaCoberta: 34.04,
        areaPrivativaDiferente: 0,
        areaVagaGaragem: 0,
        areaEquivalenteTotal: 53.6096,
        precoVendaUnitM2: 8500,
        deflatorAreaDescoberta: 0,
        cucM2: 2504.8,
        qtdSubRogada: 2,
      },
      {
        id: id("un"),
        nome: "Apt 07, 08, 13, 14, 19, 20 - sem vaga de garagem",
        qtd: 6,
        areaPrivativaCoberta: 34.09,
        areaPrivativaDiferente: 0,
        areaVagaGaragem: 0,
        areaEquivalenteTotal: 53.6596,
        precoVendaUnitM2: 8500,
        deflatorAreaDescoberta: 0,
        cucM2: 2504.8,
        qtdSubRogada: 1,
      },
      {
        id: id("un"),
        nome: "Apt 23 e 26 - cobertura + área privativa",
        qtd: 2,
        areaPrivativaCoberta: 36.16,
        areaPrivativaDiferente: 40.48,
        areaVagaGaragem: 12.5,
        areaEquivalenteTotal: 63.4696,
        precoVendaUnitM2: 10000,
        deflatorAreaDescoberta: 0,
        cucM2: 2504.8,
        qtdSubRogada: 1,
      },
      {
        id: id("un"),
        nome: "Apt 24 - cobertura + área privativa",
        qtd: 1,
        areaPrivativaCoberta: 33.63,
        areaPrivativaDiferente: 36.18,
        areaVagaGaragem: 25,
        areaEquivalenteTotal: 78.3592,
        precoVendaUnitM2: 11000,
        deflatorAreaDescoberta: 0,
        cucM2: 2504.8,
        qtdSubRogada: 0,
      },
      {
        id: id("un"),
        nome: "Apt 25 - cobertura + área privativa",
        qtd: 1,
        areaPrivativaCoberta: 33.66,
        areaPrivativaDiferente: 23.68,
        areaVagaGaragem: 12.5,
        areaEquivalenteTotal: 58.8196,
        precoVendaUnitM2: 11000,
        deflatorAreaDescoberta: 0,
        cucM2: 2504.8,
        qtdSubRogada: 0,
      },
    ],
    custoOperacional: [
      { id: id("co"), nome: "IPTU (obra)", valor: 5400, categoria: "Terreno — custos complementares" },
      { id: id("co"), nome: "ITBI + Habite-se", valor: 35660.53, categoria: "Jurídico e documentação" },
      { id: id("co"), nome: "Advogados", valor: 20000, categoria: "Jurídico e documentação" },
      { id: id("co"), nome: "Despachantes", valor: 8000, categoria: "Jurídico e documentação" },
      { id: id("co"), nome: "Registro de incorporação", valor: 60000, categoria: "Jurídico e documentação" },
      { id: id("co"), nome: "NBR 12.721", valor: 20000, categoria: "Projetos e aprovações" },
      { id: id("co"), nome: "Plantas humanizadas", valor: 65000, categoria: "Projetos e aprovações" },
      { id: id("co"), nome: "Perspectivas", valor: 60000, categoria: "Projetos e aprovações" },
      { id: id("co"), nome: "Calculista de NB", valor: 1500, categoria: "Projetos e aprovações" },
      { id: id("co"), nome: "Fundação", valor: 200000, categoria: "Projetos e aprovações" },
      { id: id("co"), nome: "Gestão de projeto", valor: 356605.25, categoria: "Administração da incorporação" },
      { id: id("co"), nome: "Folders", valor: 2500, categoria: "Comercialização e marketing" },
      { id: id("co"), nome: "Placa de venda", valor: 2500, categoria: "Comercialização e marketing" },
      { id: id("co"), nome: "Propagandas", valor: 2500, categoria: "Comercialização e marketing" },
      { id: id("co"), nome: "Elevador", valor: 150000, categoria: "Instalações e equipamentos" },
    ],
  };
}

export function novaUnidade(): EstudoState["unidades"][number] {
  return {
    id: id("un"),
    nome: "Novo tipo de unidade",
    qtd: 1,
    areaPrivativaCoberta: 0,
    areaPrivativaDiferente: 0,
    areaVagaGaragem: 0,
    areaEquivalenteTotal: 0,
    precoVendaUnitM2: 0,
    deflatorAreaDescoberta: 0,
    cucM2: 0,
    qtdSubRogada: 0,
  };
}

export function novoCustoItem(): EstudoState["custoOperacional"][number] {
  return { id: id("co"), nome: "Novo item", valor: 0, categoria: "Outros" };
}

export function estudoVazio(): EstudoState {
  return {
    nomeProjeto: "Novo estudo de viabilidade",
    terreno: { areaTerreno: 0, valorTerrenoTotal: 0, areaTotalConstruida: 0 },
    parametros: {
      tributacaoPct: 0.04,
      corretagemUnidadePct: 0.05,
      corretagemTerrenoPct: 0,
      vmvPct: 0.014,
      metaIncorporadorPct: 0.15,
      metaConstrutorPct: 0.1,
    },
    unidades: [novaUnidade()],
    custoOperacional: [],
  };
}
